---
- name: Create user with home directory
  ansible.builtin.user:
    name: "{{ username }}"
    create_home: yes
    state: present

- name: Create .bashrc with alias
  ansible.builtin.copy:
    content: 'alias la="ls -lAh"'
    dest: "/home/{{ username }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: Create .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: Create .ssh directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

- name: Add SSH public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"
