---
- name: Create user with specified username and password
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Add Git config for created user
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: username is defined
