[servers:children]
webservers
appservers


[webservers]
server1 ansible_host=89.232.188.188 ansible_user=sergei
server2 ansible_host=103.76.52.133 ansible_user=sergei

[webservers:vars]
nginx_port=8090
root_dir=/var/tmp/www

[appservers]
103.76.52.133
