[servers:children]
webservers
appservers


[webservers]
server1 ansible_host=178.154.244.168 ansible_user=sergei
server2 ansible_host=111.88.147.200 ansible_user=sergei

[webservers:vars]
nginx_port=8090
root_dir=/var/tmp/www

[appservers]
111.88.147.200

[appservers:vars]
nginx_port=8090
root_dir=/var/tmp/www
